# Generated by Django 5.1.4 on 2024-12-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_rename_date_transaction_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="temp_placeholder",
            field=models.CharField(default="", editable=False, max_length=1),
        ),
    ]
