# Generated by Django 5.1.4 on 2024-12-23 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_transaction_temp_placeholder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="temp_placeholder",
        ),
    ]
