# Generated by Django 5.1.4 on 2024-12-25 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_currency_user_transaction_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="currencies",
                to="myapp.users",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="myapp.users",
            ),
        ),
    ]
