# Generated by Django 5.1.4 on 2024-12-27 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_remove_currency_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="myapp.currency",
            ),
        ),
    ]
