# Generated by Django 5.1.4 on 2024-12-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_alter_transaction_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="old_currency",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
