# Generated by Django 5.1.4 on 2024-12-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_transaction_old_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="old_currency",
        ),
    ]
