# Generated by Django 5.1.4 on 2024-12-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_remove_transaction_old_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="balance",
            field=models.FloatField(default=0.0),
        ),
    ]
